In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('retail_sales_dataset.csv')

In [4]:
df.head(10)

,transaction_id,transaction_date,customer_id,customer_gender,customer_age_group,customer_segment,product_id,product_name,category,brand,quantity,unit_price,discount_pct,sales_amount,payment_method,sales_channel,region
0,T0000001,2024-04-24,C000820,Other,35-44,Returning,P1082,Dumbbells,Sports,Brand 1,2,313.53,20,501.65,Debit Card,Online,North
1,T0000002,2025-07-12,C002849,Other,45-54,New,P1087,Running Shoes,Sports,Brand 3,1,366.16,0,366.16,Credit Card,Online,South
2,T0000003,2025-06-01,C019727,Male,55+,Returning,P1030,Sneakers,Clothing,Brand 3,1,27.99,0,27.99,Gift Card,In-Store,South
3,T0000004,2025-08-26,C009116,Male,25-34,VIP,P1058,Sunscreen,Beauty,Brand 1,2,102.01,15,173.42,Cash,In-Store,South
4,T0000005,2024-12-10,C003350,Male,45-54,New,P1028,Sneakers,Clothing,Brand 1,1,259.55,0,259.55,Cash,In-Store,Central
5,T0000006,2024-02-14,C023912,Female,55+,New,P1034,Bread,Groceries,Brand 1,1,474.70,0,474.70,PayPal,Online,Central
6,T0000007,2025-10-05,C020268,Female,55+,Returning,P1038,Rice,Groceries,Brand 2,1,53.35,0,53.35,Credit Card,Online,South
7,T0000008,2024-10-23,C002615,Male,18-24,VIP,P1099,Board Game,Toys,Brand 3,4,17.58,0,70.32,Cash,In-Store,East
8,T0000009,2025-01-14,C011642,Male,35-44,New,P1021,Jeans,Clothing,Brand 3,1,307.87,10,277.08,Gift Card,Mobile App,South
9,T0000010,2024-09-07,C005355,Female,45-54,Loyal,P1069,Cookware Set,Home,Brand 3,1,41.90,25,31.42,Gift Card,Online,East

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 17 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   transaction_id      120000 non-null  object
 1   transaction_date    120000 non-null  object
 2   customer_id         120000 non-null  object
 3   customer_gender     120000 non-null  object
 4   customer_age_group  120000 non-null  object
 5   customer_segment    120000 non-null  object
 6   product_id          120000 non-null  object
 7   product_name        120000 non-null  object
 8   category            120000 non-null  object
 9   brand               120000 non-null  object
 10  quantity            120000 non-null  int64
 11  unit_price          120000 non-null  float64
 12  discount_pct        120000 non-null  int64
 13  sales_amount        120000 non-null  float64
 14  payment_method      120000 non-null  object
 15  sales_channel       120000 non-null  object
 16  region              120000 non-null  object
dtypes: float64(2), int64(2), object(13)
memory usage: 15.6+ MB

In [6]:
df['transaction_date'] = pd.to_datetime(df['transaction_date'])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 17 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   transaction_id      120000 non-null  object
 1   transaction_date    120000 non-null  datetime64[ns]
 2   customer_id         120000 non-null  object
 3   customer_gender     120000 non-null  object
 4   customer_age_group  120000 non-null  object
 5   customer_segment    120000 non-null  object
 6   product_id          120000 non-null  object
 7   product_name        120000 non-null  object
 8   category            120000 non-null  object
 9   brand               120000 non-null  object
 10  quantity            120000 non-null  int64
 11  unit_price          120000 non-null  float64
 12  discount_pct        120000 non-null  int64
 13  sales_amount        120000 non-null  float64
 14  payment_method      120000 non-null  object
 15  sales_channel       120000 non-null  object
 16  region              120000 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(2), object(12)
memory usage: 15.6+ MB

In [8]:
df['customer_gender'].value_counts()

customer_gender
Female    40268
Other     39906
Male      39826
Name: count, dtype: int64

In [9]:
df['customer_age_group'].value_counts()

customer_age_group
35-44    24196
55+      24078
18-24    23941
45-54    23919
25-34    23866
Name: count, dtype: int64

In [10]:
df['customer_segment'].value_counts()

customer_segment
VIP          30115
New          30020
Loyal        30014
Returning    29851
Name: count, dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df['transaction_id'].duplicated().sum()

np.int64(0)

In [13]:
df[['quantity', 'unit_price', 'discount_pct', 'sales_amount']].describe()

            quantity     unit_price   discount_pct   sales_amount
count  120000.000000  120000.000000  120000.000000  120000.000000
mean        1.662908     240.621785       5.496500     377.975454
std         1.014291     146.457057       8.193257     356.893357
min         1.000000       7.730000       0.000000       5.410000
25%         1.000000     102.010000       0.000000     136.860000
50%         1.000000     238.750000       0.000000     295.980000
75%         2.000000     379.000000      10.000000     461.500000
max         5.000000     493.510000      30.000000    2467.550000

In [14]:
df['calculated_sales'] = (
    df['quantity'] * df['unit_price'] * (1 - df['discount_pct'] / 100)
)

In [15]:
(df['sales_amount'] - df['calculated_sales']).abs().describe()

count    120000.00000
mean          0.00092
std           0.00154
min           0.00000
25%           0.00000
50%           0.00000
75%           0.00200
max           0.00500
dtype: float64

In [16]:
df.drop(columns='calculated_sales', inplace=True)

In [17]:
print("Data inicial:", df['transaction_date'].min())
print("Data final:", df['transaction_date'].max())

Data inicial: 2024-01-01 00:00:00
Data final: 2025-12-30 00:00:00

In [18]:
print("Categorias:")
print(df['category'].value_counts())

print("\nMarcas:")
print(df['brand'].nunique())

print("\nProdutos:")
print(df['product_name'].nunique())

print("\nCanais:")
print(df['sales_channel'].value_counts())

print("\nRegiões:")
print(df['region'].value_counts())

print("\nMétodos de pagamento:")
print(df['payment_method'].value_counts())

Categorias:
category
Sports         15218
Clothing       15156
Beauty         15073
Groceries      15034
Toys           15022
Electronics    15008
Home           14933
Books          14556
Name: count, dtype: int64

Marcas:
3

Produtos:
40

Canais:
sales_channel
Mobile App    40204
In-Store      40049
Online        39747
Name: count, dtype: int64

Regiões:
region
Central    24244
North      24075
South      24066
West       23950
East       23665
Name: count, dtype: int64

Métodos de pagamento:
payment_method
Credit Card    24262
Cash           24034
PayPal         23998
Debit Card     23897
Gift Card      23809
Name: count, dtype: int64

In [19]:
df['region'].value_counts()

region
Central    24244
North      24075
South      24066
West       23950
East       23665
Name: count, dtype: int64

In [20]:
df['payment_method'].value_counts()

payment_method
Credit Card    24262
Cash           24034
PayPal         23998
Debit Card     23897
Gift Card      23809
Name: count, dtype: int64

Conclusão – Compreensão e Qualidade dos Dados

A análise inicial mostrou que o dataset contém 120.000 transações e 17 variáveis, abrangendo o período de janeiro de 2024 a dezembro de 2025. Não foram identificados valores ausentes, registros duplicados ou IDs de transação repetidos. A variável transaction_date foi convertida para o formato datetime, e as variáveis numéricas apresentaram valores dentro de intervalos plausíveis. Além disso, o sales_amount foi validado com base na quantidade, preço unitário e desconto, apresentando apenas pequenas diferenças decorrentes de arredondamentos.

A análise das variáveis categóricas identificou 8 categorias de produtos, 40 produtos, 3 marcas e 3 canais de venda, com uma distribuição bastante equilibrada entre as categorias e canais. Os segmentos de clientes e grupos etários também apresentam uma distribuição semelhante entre si.

De modo geral, os dados apresentam boa qualidade e estão estruturados de forma consistente, sendo adequados para avançar para a Análise Exploratória de Dados (EDA).

In [22]:
df.to_csv("retail_sales_clean.csv", index=False)